### ISSUE TITLE
Windows version requires MinGW

### ISSUE THREAD

**Issue by pokemonlover1234** [ronitsinha/almia-randomizer#2]
Hello - when I was setting up earlier, I noticed that the Windows version will throw up a missing DLL error if you dont have MinGW installed (I looked up the dll). I managed to run the linux version through WSL.

Can you either remove that dependency somehow, see if bundling the DLL in the release would work, or make the dependency clear in the Readme?

**Comment by pokemonlover1234** [comment]
I just realized I didnt actually post the DLL thats required. Not at my pc rn. I'll update tomorrow.

**Comment by pokemonlover1234** [comment]
![image](https://github.com/ronitsinha/almia-randomizer/assets/18287167/c417e030-3566-4e0e-97c4-2ae659d31cf4)
Apologies for the delay

Through a dependency viewer, I have also seen that it needs libstdc++-6.dll

**Comment by ronitsinha** [comment]
Thanks for bringing this to my attention. I'll look into making the build work without unspecified dependencies.
